@file:JvmName("Program")
package gay.pizza.CavesOfJolk

import com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application
import com.badlogic.gdx.backends.lwjgl3.Lwjgl3ApplicationConfiguration
import com.badlogic.gdx.graphics.glutils.HdpiMode

fun main()
{
	//val conf = Lwjgl3WindowConfiguration()
	val conf = Lwjgl3ApplicationConfiguration()
	conf.setTitle("Caves of Jolk: Ultimate Edition")
	conf.setHdpiMode(HdpiMode.Logical)
	//conf.useVsync(false)
	//conf.setForegroundFPS(300)
	conf.setWindowedMode(1280, 720)
	conf.setResizable(true)
	Lwjgl3Application(Game(), conf)
}
